### PR TITLE
Add method to generate LaTex formatted string

### LINKED ISSUE #131: Add a get_latex_string() method
### Is your feature request related to a problem? Please describe.

Unable to get code that produces the table in LaTex.

### Describe the solution you'd like

Add a get_latex_string() method that returns latex code which reproduces the table in LaTex. Should be very similar to the get_html_string() method.

### Describe alternatives you've considered

Get string in Markdown format and translate them into latex code using other tools, eg [https://tableconvert.com/](https://tableconvert.com/). 

### Additional context
The prettytable counterpart in Julia has the desired feature:
[https://ronisbr.github.io/PrettyTables.jl/stable/man/latex_backend/](https://ronisbr.github.io/PrettyTables.jl/stable/man/latex_backend/)

### PR DESCRIPTION
**Pull request by kinianlo**
Resolve #131 
Add a method to get LaTex formatted code, similar to how `get_html_string()` works.
### Simple (no formatting)
```python
x = prettytable.PrettyTable()
x.field_names = ["Field 1", "Field 2", "Field 3"]
x.add_row(["value 1", "value 2", "value 3"])
x.add_row(["value 1", "value 2", "value 3"])
x.add_row(["value 1", "value 2", "value 3"])

latex_str = x.get_latex_string()
print(latex_str)
```
gives the output
```latex
\begin{tabular}{ccc}
Field 1 & Field 2 & Field 3 \\
value 1 & value 2 & value 3 \\
value 1 & value 2 & value 3 \\
value 1 & value 2 & value 3 \\
\end{tabular}
```
which looks like the following gif when rendered by LaTex:

CodeCogsEqn (2)

### With formatting
```python
x = prettytable.PrettyTable()
x.field_names = ["Field 1", "Field 2", "Field 3"]
x.add_row(["value 1", "value 2", "value 3"])
x.add_row(["value 1", "value 2", "value 3"])
x.add_row(["value 1", "value 2", "value 3"])

latex_str = x.get_latex_string(format=True, border=True, hrules=prettytable.ALL, vrules=prettytable.FRAME)
print(latex_str)
```
gives the output 
```latex
\begin{tabular}{|ccc|}
\hline
Field 1 & Field 2 & Field 3 \\
\hline
value 1 & value 2 & value 3 \\
\hline
value 1 & value 2 & value 3 \\
\hline
value 1 & value 2 & value 3 \\
\hline
\end{tabular}
```
which looks like the following gif when rendered by LaTex:

CodeCogsEqn (3)

### CODE REVIEW

**Comment by kinianlo** [comment]
There is actually an ambiguity in the `HEADER` option of `option["hrules"]`, as in it is unclear how the `HEADER` option should look like.  I've tried to look at the code base to identify the correct behaviour but I found no part of the code actually uses the `HEADER` option. 
I have thought of the following three possibilities:
### First behaviour

CodeCogsEqn (4)

### Second behaviour

CodeCogsEqn (5)


### Third behaviour
CodeCogsEqn (6)

I have arbitrarily chosen to implement the second behaviour.  I think these three are all reasonable behaviours and we should have separate options for all of them? Or there are other style options that are designed for this?

**Comment by hugovk** [comment]
Thank you for the PR!

I see the `HEADER` option for `hrules` was added in this commit back in 2013:

* https://github.com/jazzband/prettytable/commit/4b9da67e0504ecddeaafaea9328dc6810de5f1a9

Commit message:

> Implemented the totally unobjectionable parts of the enhancement sugg…
> …ested in Issue 22.
>
> Made formatted HTML output more closely mirror ASCII output.

That will be issue 22 in the old Google Code issue tracker:

* https://code.google.com/archive/p/prettytable/issues/22

Which explains:


> Hi, thanks for this suggestion.
> 
> I have made changes to the SVN trunk such that it is now partially possible to get the styles you want.
> 
> The "hrules" attribute, which could previously take values FRAME, ALL or NONE can now also be set to HEADER, which prints a hrule only under the header, like your first example.
> 
> In addition to the old "hrules" attribute, there is now also "vrules", which can be take values FRAME, ALL or NONE.
> 
> By setting hrules=HEADER and vrules=NONE, along with horizontal_character="=" and junction_character="=", it should be possible to achieve the first example table you gave.
> 
> By setting hrules=FRAME and vrules=FRAME, you can get something close to your second example, the only difference being that you still won't have - as the horizontal character for the frame and = as the horizontal character for the header.
> 
> I may add the option for two different kind of horizontal characters, or I may not, I am not sure yet. It seems harmless enough, but if I do that, then somebody will want the ability to, e.g, make a table like this:
> 
> +=====+=====+ | Foo . Bar | +-----+-----+ | 1 . 2 | +=====+=====+
> 
> i.e. where the external rules are different from the internal rules, and then if I do that somebody will want something else, and before you know it instead of just horizontal_char, vertical_char and junction_char there will have to be 12 different attributes controlling the way lines are drawn to cover all the edge cases...
> 
> In general I am not opposed to putting in stuff to let people tweak their tables in all the little ways they want, but only if that doesn't make it difficult for the majority of people to do simple things. If someone just wants to use, say, "=" as their horizontal line everywhere, they should be able to do that by setting one attribute, and should not be forced to set 3 or 4 attributes corresponding to all the different kinds of horizontal line if they don't care about the differences.

Testing, it works as described:

```pycon
>>> x.hrules=prettytable.FRAME
>>> print(x)
+-----------+------+------------+-----------------+
| City name | Area | Population | Annual Rainfall |
+-----------+------+------------+-----------------+
|  Adelaide | 1295 |  1158259   |      600.5      |
|  Brisbane | 5905 |  1857594   |      1146.4     |
|   Darwin  | 112  |   120900   |      1714.7     |
|   Hobart  | 1357 |   205556   |      619.5      |
|   Sydney  | 2058 |  4336374   |      1214.8     |
| Melbourne | 1566 |  3806092   |      646.9      |
|   Perth   | 5386 |  1554769   |      869.4      |
+-----------+------+------------+-----------------+
>>> x.hrules=prettytable.HEADER
>>> print(x)
| City name | Area | Population | Annual Rainfall |
+-----------+------+------------+-----------------+
|  Adelaide | 1295 |  1158259   |      600.5      |
|  Brisbane | 5905 |  1857594   |      1146.4     |
|   Darwin  | 112  |   120900   |      1714.7     |
|   Hobart  | 1357 |   205556   |      619.5      |
|   Sydney  | 2058 |  4336374   |      1214.8     |
| Melbourne | 1566 |  3806092   |      646.9      |
|   Perth   | 5386 |  1554769   |      869.4      |
>>> x.hrules=prettytable.ALL
>>> print(x)
+-----------+------+------------+-----------------+
| City name | Area | Population | Annual Rainfall |
+-----------+------+------------+-----------------+
|  Adelaide | 1295 |  1158259   |      600.5      |
+-----------+------+------------+-----------------+
|  Brisbane | 5905 |  1857594   |      1146.4     |
+-----------+------+------------+-----------------+
|   Darwin  | 112  |   120900   |      1714.7     |
+-----------+------+------------+-----------------+
|   Hobart  | 1357 |   205556   |      619.5      |
+-----------+------+------------+-----------------+
|   Sydney  | 2058 |  4336374   |      1214.8     |
+-----------+------+------------+-----------------+
| Melbourne | 1566 |  3806092   |      646.9      |
+-----------+------+------------+-----------------+
|   Perth   | 5386 |  1554769   |      869.4      |
+-----------+------+------------+-----------------+
>>> x.hrules=prettytable.NONE
>>> print(x)
| City name | Area | Population | Annual Rainfall |
|  Adelaide | 1295 |  1158259   |      600.5      |
|  Brisbane | 5905 |  1857594   |      1146.4     |
|   Darwin  | 112  |   120900   |      1714.7     |
|   Hobart  | 1357 |   205556   |      619.5      |
|   Sydney  | 2058 |  4336374   |      1214.8     |
| Melbourne | 1566 |  3806092   |      646.9      |
|   Perth   | 5386 |  1554769   |      869.4      |
````

Your three options all match the description ("can now also be set to HEADER, which prints a hrule only under the header"), so go with whichever option you find most pleasing.

Does this help?

**Comment by kinianlo** [comment]
Thanks for the comment! I think I will opt for the first behaviour listed above as it matches with the example you showed in the comment.

**Comment by hugovk** [comment]
Thank you! Looking good. It'd be nice to add tests to cover the few lines not covered, do you think that's doable?

https://github.com/jazzband/prettytable/pull/133/files

**Comment by kinianlo** [comment]
Yes of course! will do.

**Comment by hugovk** [comment]
Thank you for your contribution!

**Pull request merged**
