### PR TITLE
Use `<caption>` tags to print html table titles

### PR DESCRIPTION
**Pull request by daibhid**
This is a potential fix for issue #159

### CODE REVIEW

**Comment by hugovk** [comment]
Thank you, `<caption>` looks much more suitable. It's also possible for the user to style it with CSS to choose which side to put it. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption

Please could you add tests?

**Comment by hugovk** [comment]
Looks good, would it also be possible to add one for the change in `_get_formatted_html_string` as well? I realise neither of these were tested/covered before, but now's the perfect opportunity to improve that.

**Comment by daibhid** [comment]
> Looks good, would it also be possible to add one for the change in `_get_formatted_html_string` as well? I realise neither of these were tested/covered before, but now's the perfect opportunity to improve that.

Yes, I'd be happy to, will update this soon

**Comment by hugovk** [comment]
Thank you for the report and pull request!

**Comment by hugovk** [comment]
Released in PrettyTable 3.0.0, thanks again!

**Pull request merged**
