### PR TITLE
Add Escaping Options to HTML Tables

### LINKED ISSUE #40: Make escaping data in an HTML table optional
For certain rows, I require the data to be augmented with HTML, and that unfortunately gets escaped here: https://github.com/jazzband/prettytable/blob/master/prettytable.py#L1622

Would you consider adding an option to get_html_string to disable data escaping?

Happy to contribute a PR

### PR DESCRIPTION
**Pull request by geekiegirl2016**
Fixes #40. 

Add Escaping Options to HTML Tables

This will allow tables to contain active links and other html code allowing prettytables to more easily be used for dynamic site building.

Example includes allowing a header to be a link.

`x.get_html_string(header_escape=False, data_escape=False)`

```html
<table>
    <thead>
        <tr>
            <th><a href="https://google.com">Field 1</a></th>
            <th>Field 2</th>
        </tr>
    </thead>
        <tr>
            <td>value 1</td>
            <td>value 2</td>
        </tr>
        <tr>
            <td><a href="https://google.com">value 3</a></td>
            <td>value 4</td>
        </tr>
    </tbody>
</table>
```

instead of
`x.get_html_string()`

```html
<table>
    <thead>
        <tr>
            <th>&lt;a href=&quot;https://google.com&quot;&gt;Field 1&lt;/a&gt;</th>
            <th>Field 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>value 1</td>
            <td>value 2</td>
        </tr>
        <tr>
            <td>&lt;a href=&quot;https://google.com&quot;&gt;value 3&lt;/a&gt;</td>
            <td>value 4</td>
        </tr>
    </tbody>
</table>
```

### CODE REVIEW

**Comment by geekiegirl2016** [comment]
#40 Was previously identified

**Comment by hugovk** [comment]
Thank you for the PR!

Please could you:

* Name them `escape_header` and `escape_data`
* Mention them in the README
* Fix the lint check

**Comment by geekiegirl2016** [comment]
Made the changes that were asked for, hopefully correctly 😁

**Comment by hugovk** [comment]
The tests are failing after merging master into this branch, I expect it's from the changes from https://github.com/jazzband/prettytable/pull/115 / https://github.com/jazzband/prettytable/pull/104.

@guysz Please could you advise what's needed here? Thanks!

**Comment by guysz** [comment]
Adding properties for `escape_header` and for `escape_data` should fix it.
e.g.:
```python
    @property
    def escape_header(self):
        """Escapes the text within a header (True or False)"""
        return self._escape_header

    @escape_header.setter
    def escape_header(self, val):
        self._validate_option("escape_header", val)
        self._escape_header = val


    @property
    def escape_data(self):
        """Escapes the text within a data field (True or False)"""
        return self._escape_data

    @escape_data.setter
    def escape_data(self, val):
        self._validate_option("escape_data", val)
        self._escape_data = val
```

**Comment by hugovk** [comment]
@geekiegirl2016 Happy new year! Would you like to try adding the properties above? Let me know if need a hand resolving the conflicts.

**Pull request closed without merging**
