### PR TITLE
Improve `TableHandler` type annotations

### PR DESCRIPTION
**Pull request by cdce8p**

### CODE REVIEW

**Comment by hugovk** [comment]
I just moved mypy from pre-commit to tox so it can be tested with a full install (https://github.com/jazzband/prettytable/pull/321), please could you rebase or merge `main` into both these PRs?

**Comment by hugovk** [comment]
Thanks! I was going to make a release today, but there's no rush and if you have more stuff to come, I can hold off a bit if you prefer?

**Comment by cdce8p** [comment]
> Thanks! I was going to make a release today, but there's no rush and if you have more stuff to come, I can hold off a bit if you prefer?

I might have one or two more PRs. The difficult part is actually to group the changes in a way that makes sense logically and is easy to review.

**Comment by hugovk** [comment]
I appreciate these have been in bitesize reviewable chunks :)

**Pull request merged**
