### PR TITLE
Test on Python 3.10 final

### LINKED ISSUE #142: Test on Python 3.10 final
image

Python 3.10 final was released this month:

* https://discuss.python.org/t/python-3-10-0-is-now-available/10955

That means we can switch testing from `3.10-dev` to `3.10` on the CI.

Edit the CI config file to switch, but note this:

* https://dev.to/hugovk/the-python-3-1-problem-85g

And put quotes around all the Python versions.

### PR DESCRIPTION
**Pull request by NarayanAdithya**
Fixes #142

### CODE REVIEW

**Comment by hugovk** [comment]
Please keep them as double quotes, thanks.

**Comment by NarayanAdithya** [comment]
Okay, will change it to double quotes

**Comment by hugovk** [comment]
It was failing due to the single quotes, but pre-commit is passing now! 👍

**Comment by hugovk** [comment]
Merged, thank you!

**Pull request merged**
