### PR TITLE
Fixed JSON object

### PR DESCRIPTION
**Pull request by KoraiD**
JSON should contain relevant data from the first object so the iterator should pick it up as a row and not just as the header.

### CODE REVIEW

**Comment by KoraiD** [comment]
@hugovk, can you please help me to see if there is anything I should change in my request to get it merged?

**Comment by hugovk** [comment]
Please could you start off by explaining why this change is needed and what you're expecting?

The bug report template may help us :)


### What did you do?

### What did you expect to happen?

### What actually happened?

### What versions are you using?

* OS: 
* Python: 
* PrettyTable: 

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python
# code goes here
```

**Comment by KoraiD** [comment]
Right, sorry that I missed the bug report template. :D

# What did you do?
I used the Prettytable `from_json()` function to parse a JSON file and print it as a table.

# What did you expect to happen?
My expectation is that each element of the standard JSON object will be represented as individual lines.

# What actually happened?
The first element of the JSON object was used as a header, but got skipped in the iterator that converts the elements to rows. So, the first element of the JSON object was missing from the table.

# What versions are you using?

* OS: macOS 12.6
* Python: 3.8.13
* PrettyTable: 3.4.1

Code that reproduces the issue:

```python
from prettytable import from_json
import json

test_json = [
	{"Name": "FirstEmployee", "Scores": 20000},
	{"Name": "SecondEmployee", "Scores": 31000},
	{"Name": "ThirdEmployee", "Scores": 14000}
]
table = from_json(json.dumps(test_json))
print(table)
```

Result:
```
+----------------+--------+
|      Name      | Scores |
+----------------+--------+
| SecondEmployee | 31000  |
| ThirdEmployee  | 14000  |
+----------------+--------+
```

Expected result:
```
+----------------+--------+
|      Name      | Scores |
+----------------+--------+
| FirstEmployee  | 20000  |
| SecondEmployee | 31000  |
| ThirdEmployee  | 14000  |
+----------------+--------+
```

Solution:
`prettytable.py` line 2404

```python
    def from_json(json_string, **kwargs):
      table = PrettyTable(**kwargs)
      objects = json.loads(json_string)
      table.field_names = objects[0]
      for obj in objects[0:]: # ---> changed from for obj in objects[1:]:
          row = [obj[key] for key in table.field_names]
          table.add_row(row)
    return table
```

**Comment by hugovk** [comment]
Thanks!

PrettyTable expects the JSON to start with the headers. For example add `["Name", "Scores"],`:

```python
from prettytable import from_json
import json

test_json = [
    ["Name", "Scores"],
	{"Name": "FirstEmployee", "Scores": 20000},
	{"Name": "SecondEmployee", "Scores": 31000},
	{"Name": "ThirdEmployee", "Scores": 14000}
]
table = from_json(json.dumps(test_json))
print(table)
```
```
+----------------+--------+
|      Name      | Scores |
+----------------+--------+
| FirstEmployee  | 20000  |
| SecondEmployee | 31000  |
| ThirdEmployee  | 14000  |
+----------------+--------+
```

This is useful as you can easily switch the order:

```python
from prettytable import from_json
import json

test_json = [
	["Scores", "Name"],
	{"Name": "FirstEmployee", "Scores": 20000},
	{"Name": "SecondEmployee", "Scores": 31000},
	{"Name": "ThirdEmployee", "Scores": 14000}
]
table = from_json(json.dumps(test_json))
print(table)
```
```
+--------+----------------+
| Scores |      Name      |
+--------+----------------+
| 20000  | FirstEmployee  |
| 31000  | SecondEmployee |
| 14000  | ThirdEmployee  |
+--------+----------------+
```

Or just print out one:

```python
from prettytable import from_json
import json

test_json = [
	["Scores"],
	{"Name": "FirstEmployee", "Scores": 20000},
	{"Name": "SecondEmployee", "Scores": 31000},
	{"Name": "ThirdEmployee", "Scores": 14000}
]
table = from_json(json.dumps(test_json))
print(table)
```
```
+--------+
| Scores |
+--------+
| 20000  |
| 31000  |
| 14000  |
+--------+
```

**Comment by KoraiD** [comment]
Got it, thanks for the detailed explanation!

**Comment by hugovk** [comment]
You're welcome!

**Pull request closed without merging**
